### ISSUE TITLE
Multinode problem, missing decisions

### ISSUE THREAD

**Issue by websitesca** [crowdsecurity/go-cs-bouncer#47]
Hi, thanks for all your work on Crowdsec, it is really great.

We've noticed a problem when working with the `caddy-crowdsec-bouncer` for Caddy server. Some decisions don't reach certain nodes randomly.

For example, say there are 2 nodes, A and B (each communicates with 1 LAPI on another server). If I block my own IP on the LAPI, I will see a debug log entry on A that the IP was added, but won't see it on node B.

Then to make matters even worse. If I delete my IP from the decisions on the LAPI, I may see the delete on node B but not A.

Thus the IP stays blocked on A and was never blocked on B, which is not good.

Just wondering if you had ideas on where to look. Would be happy to work on a PR.

**Comment by LaurenceJJones** [comment]
Please make sure each node is using a unique api key, as LAPI tracks what decisions each node has been informed about based on the api key.

**Comment by blotus** [comment]
Hello,

Are you using the same API key for both bouncers ?
If so, that's an unsupported configuration at the moment, but we have started some work to address this (see this [issue](https://github.com/crowdsecurity/crowdsec/issues/3255), we should have a PR fixing it fairly soon)

**Comment by websitesca** [comment]
Gotcha, thank you!
